//
// Created by adrian on 03.05.20.
//

import Foundation
import CustomGraphicsMath

// TODO: might implement a rawMouseEvent or systemMouseEvent and a UIMouseEvent (with more properties added for proper use in ui, generated by UIRoot from RawMouseEvent)
public protocol MouseEvent {
    var position: DPoint2 { get set }
}

public struct MouseButtonUpEvent: MouseEvent {
    public var button: MouseButton
    public var position: DPoint2

    public init(button: MouseButton, position: DPoint2) {
        self.button = button
        self.position = position
    }
}

public struct MouseButtonDownEvent: MouseEvent {
    public var button: MouseButton
    public var position: DPoint2

    public init(button: MouseButton, position: DPoint2) {
        self.button = button
        self.position = position
    }
}

public struct MouseWheelEvent: MouseEvent {
    public var scrollAmount: DVec2
    public var position: DPoint2

    public init(scrollAmount: DVec2, position: DPoint2) {
        self.scrollAmount = scrollAmount
        self.position = position
    }
}

public struct MouseMoveEvent: MouseEvent {
    public var position: DPoint2
    public var previousPosition: DPoint2
    public var move: DVec2 {
        get {
            DVec2(position.x - previousPosition.x, position.y - previousPosition.y)
        }
    }

    public init(position: DPoint2, previousPosition: DPoint2) {
        self.position = position
        self.previousPosition = previousPosition
    }
}

public struct MouseEnterEvent: MouseEvent {
    public var position: DPoint2
    public var previousPosition: DPoint2
    public var move: DVec2 {
        get {
            DVec2(position.x - previousPosition.x, position.y - previousPosition.y)
        }
    }

    public init(position: DPoint2, previousPosition: DPoint2) {
        self.position = position
        self.previousPosition = previousPosition
    }
}

public struct MouseLeaveEvent: MouseEvent {
    public var position: DPoint2
    public var previousPosition: DPoint2
    public var move: DVec2 {
        get {
            DVec2(position.x - previousPosition.x, position.y - previousPosition.y)
        }
    }

    public init(position: DPoint2, previousPosition: DPoint2) {
        self.position = position
        self.previousPosition = previousPosition
    }
}